version: '3'

volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/jaehyuki/data
      o: bind
      type: none

services:
  nginx:
    container_name: nginx

    build:
      context: ./requirements/nginx/
      dockerfile: ./Dockerfile
    ports:
    - 443:443
    networks:
      - hyukinet
    env_file:
      - .env

  mariadb:
    container_name: mariadb

    build:
      context: ./requirements/mariadb/
      dockerfile: ./Dockerfile
    networks:
      - hyukinet
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql
      
networks:
  hyukinet:
    name: hyukinet